# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/pipulate',
                'doc_host': 'https://miklevin.github.io',
                'git_url': 'https://github.com/miklevin/pipulate',
                'lib_path': 'pipulate'},
  'syms': {'pipulate.core': {'pipulate.core.foo': ('core.html#foo', 'pipulate/core.py')}}}
